language: node_js
node_js:
    - "node"
script:
    - yarn build
branches:
    only:
        - source

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: public
    target_branch: master
    on:
        branch: source
